### ISSUE TITLE
Next release TODO

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [iamdefinitelyahuman/eth-event#4]
- [x] set up travis CI with coveralls
- [x] add badges to `readme.MD`
- [x] write a basic test suite
- [x] update readme docs
